version: '3.7'
services:
  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-south-1
      - AWS_DEFAULT_REGION=ap-south-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566:4566'